version: 2

build:
  os: ubuntu-20.04

sphinx:
  configuration: docs/source/conf.py
  
formats:
  - pdf

python:
 version: "3.9"
 install:
# - requirements: requirements/requirements.txt
 - requirements: docs/source/requirements.txt
