name: Pylint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ 3.9, '3.10']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install --upgrade -r requirements/lint.txt
          pip install --upgrade -r requirements/requirements.txt
      - name: Lint everything with flake8
        run: |
          flake8 whist --count --show-source --statistics
      - name: Lint sources with pylint
        run: |
          pylint whist
