name: Python CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.10', '3.11', '3.12' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: Whist-Team/actions/setup-poetry@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Pytest
        run: 'poetry run python -m pytest --cov=whist_core --cov-report=xml --cov-config=.coveragerc'

      - name: Upload to codecoverage
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

